name: pocket_tasks
description: A task management app with Riverpod and Hive.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # State management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  path_provider: ^2.1.1
  # UI
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # Code generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1
  # Testing
  mockito: ^5.4.3

flutter:
  uses-material-design: true
